### ISSUE TITLE
json files & understanding

### ISSUE THREAD

**Issue by firelook** [CrimsonMods/CrimsonQuest#1]
hello,

1/please do you have example  for quest_givers.json ?
=> is it usefull ? it is empty with no example

2/by default we fill quest_list.json and that's all?
it is working automaticcaly ?
if I do the action requested in the file but I have no result, did I do something wrong ?

thanks in advance for your help

P.S.
this is the file I did but the quest counter doesn't work I never succeed
[quest_list.json](https://github.com/user-attachments/files/16319244/quest_list.json)
I do not know what to put in this
[quest_givers.json](https://github.com/user-attachments/files/16319249/quest_givers.json)
=> I put 
`[
  {
    "Name": "Fire 1",
    "PrefabGUID": -1810631919,
    "QuestsToGive": [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23],
    "QuestType": 0,
    "giverEntity": {},
    "config": {
      "IsEnabled": true,
      "X": -2311.538,
	  "Y": 10.000004,
      "Z": -1010.3285,
      "Immortal": false,
      "CanMove": false,
      "AutoRespawn": true
    }
  }
]`

but it doesn't spawn automatically
I am using where am i and put the 3 coordonates
If I call it with .cq spawn => I have .vcf with internal error => and it is a standard seller

**Comment by firelook** [comment]
if I do .cq add "Fire 1" 1
it seems working but nothing in reality happen

**Comment by SkyTech6** [comment]
Yea the actual quest giver system is finicky. I recommend generating them with the VCF commands and spawning them with the command as well. 

Then editing their Json for their quest IDs to give. 

To accept a quest from them, you gotta use the accept command within range of them. 

As for why your quests don't track progress. You have them all set to Type 0, which is ItemFetch, try Type 1 for MobKill

**Comment by firelook** [comment]
unfortunately the ID is not working with editing the json manually, we have the list from like it is from a normal vendor, nothing added linked to the quest
using the command is not saved and add nothing (he syaed it is working but no ;) )

**Comment by firelook** [comment]
Do you have an example of a vendor and a quest working please ?
1/ vendor: still "his" usual selling, nothing added linked to the quest id
2/ I look at your exemple and their is nothing linked to "As for why your quests don't track progress. You have them all set to Type 0, which is ItemFetch, try Type 1 for MobKill"

thanks for your help

**Comment by firelook** [comment]
do you have .cq weekly please ?

**Comment by firelook** [comment]
close from improvment, test in progress
