### ISSUE TITLE
limit in quest taken

### ISSUE THREAD

**Issue by firelook** [CrimsonMods/CrimsonQuest#2]
I put
`## The max amount of daily quests a player can complete in one day
# Setting type: Int32
# Default value: 5
MaxDailies = 50

## The max amount of weekly quests a player can complete in a week
# Setting type: Int32
# Default value: 3
MaxWeeklies = 15`

in the config
but still lock at 3
=> in your code you put:
`if (progress.DailyQuests.Count >= 3 ) return;`
and 
also
` if (progress.WeeklyQuests.Count >= 3) return;`

is it the problem ?

**Comment by SkyTech6** [comment]
Ah I hard coded them? Yea I can fix that.

**Comment by SkyTech6** [comment]
Wait no, I think you're confusing the max amount they can take at once and the max they can complete in the time frame. The hard-coded 3 is how many they can have active/in-progress at once.
